// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yipsbfttmpfeqzxxoiiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcHNiZnR0bXBmZXF6eHhvaWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTA5MzYsImV4cCI6MjA1ODI2NjkzNn0.YZZPdPQq0iut0M1GFLiz4SuxylfZ5fEq5OSGFFKtVR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);